### ISSUE TITLE
gmd images aren't showing good on certain devices (with custom roms and theme engine)

### ISSUE THREAD

**Issue by javiersantos** [mikepenz/Android-Iconics#90]
I've been using Android Iconics for a long time in my apps. When I saw my app at my friend's phone I noticed that the images using `google-material-typeface` wasn't showing properly (both IconicsTextView and IconicsImageView).

You can see the result on my device and my friend's device. It's so so strange, it only happens with `google-material-typeface`, I'm also using `community-material-typeface` but they look OK on both devices.

OnePlus device with Euphoria 5.1.1:
![img_2015-10-19 20 15 55](https://cloud.githubusercontent.com/assets/2229658/10586882/c4f05e18-769e-11e5-9fee-d91fbb3dbf76.jpg)

Nexus 4 device with CM12.1 (my device):
![img_2015-10-19 20 15 59](https://cloud.githubusercontent.com/assets/2229658/10586883/c51621ca-769e-11e5-8a9f-35e060452ebc.jpg)

**Comment by mikepenz** [comment]
@javiersantos could it be that your friend has a custom font defined on his device? it seems that the theme framework changes icons too sometimes.

**Comment by javiersantos** [comment]
@mikepenz just talked with him, but he is using the stock theme & font.

**Comment by mikepenz** [comment]
@javiersantos hmmm :/ 

the **community-material** icons have a different unicode range so they are not overwriten. 

no default "custom" theme? :/ i have no device with CM so i can't test. But i had a report from one guy who had a custom font which broke the icon font.

**Comment by mikepenz** [comment]
on your OnePlus it's fine? Does it allow to modify themes? probably we can do some testing?

**Comment by timrae** [comment]
A user has reported a similar issue with the AnkiDroid 2.5 beta:

> when I go on the menu on Motorola E 2nd Gen (2015) Lollipop 5.1.1 it shows the image below. I installed on my tablet that is android version 4.1.2 and it works and show the menu with out any issues. 

![screenshot_2015-10-20-23-48-36](https://cloud.githubusercontent.com/assets/2818274/10627339/275356d2-77f3-11e5-9499-068f2df8477f.png)

This is what it's supposed to look like:
![screenshot_2015-10-20-14-54-21](https://cloud.githubusercontent.com/assets/2818274/10627353/51d3d71a-77f3-11e5-8706-9df06aad67a1.png)

**Comment by mikepenz** [comment]
@timrae , @javiersantos i will upload a SNAPSHOT of the Google Material Icons today with a modified unicode character mapping range. It will need someone with this issue to try the font then?

**Comment by javiersantos** [comment]
Sure. I will test the SNAPSHOT on both devices and let you know if it is working properly.

**Comment by mikepenz** [comment]
@javiersantos i've uploaded a **SNAPSHOT**

use it like this:

```gradle
dependencies {
    compile 'com.mikepenz:google-material-typeface:1.2.0.2-SNAPSHOT@aar'
}
```
you have to add the **SNAPSHOT** repository for this to work
```gradle
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by javiersantos** [comment]
Hi @mikepenz. I'm experiencing some issue with this SNAPSHOT.

On my device (where 1.2.0.1 was showing the images properly) now displays: 
```
E/Iconics: Wrong icon name: gm_highlight_off
```

Within the next hours I will test this SNAPSHOT on the device where the images of the 1.2.0.1 version were broken.

**Comment by mikepenz** [comment]
@javiersantos to be able to change the unicode mapping i used the GoogleMaterial font from icomoon. it seems **gm_highlight_off** does not exist. only ** gmd_highlight_remove**

**Comment by mikepenz** [comment]
@javiersantos i will look for a better solution (to be equal to the old mappings) later. First to make sure this change will fix the mapping problems as described with custom roms

**Comment by mikepenz** [comment]
@javiersantos ok found a better way to change the icon mapping. should be the same as with the previous version now just with a different unicode character:

```gradle
dependencies {
    compile 'com.mikepenz:google-material-typeface:1.2.0.3-SNAPSHOT@aar'
}
```

**Comment by mikepenz** [comment]
@javiersantos does the new SNAPSHOT look better?

**Comment by timrae** [comment]
I don't have a device that can test this... @javiersantos your input would be appreciated

**Comment by javiersantos** [comment]
Sorry for the delay, it was difficult to test it on both devices (the
second one is not mine).

I will have the results later today.

**Comment by mikepenz** [comment]
@javiersantos ok thank you so much.
@timrae thanks.

I also asked someone else but he was not able to reproduce it anymore :/ strange thing.

**Comment by javiersantos** [comment]
I have been testing the latest SNAPSHOT, with and without ProGuard.

It continues with the same issue. Nexus 4 (my device) displays the icons properly, but the other device shows nothing I have been testing the latest SNAPSHOT, with and without ProGuard.

It continues with the same issue. The Nexus 4 device (my device) displays the icons properly, but the other device shows nothing (instead of showing another icon, as happenned in the current stable release).

Sorry if I can't provide you the logcat, I don't have the device in my hands.

**Comment by mikepenz** [comment]
Thank you so much for testing. If I only could reproduce it on my side of any phone. 

But it seems to be a big limited to cyanogenmod + theme

**Comment by mikepenz** [comment]
@javiersantos but it's working with the Community Material Design Icons?

**Comment by javiersantos** [comment]
Yes @mikepenz. Replace `gmd` to `cmd` was my solution to solve the issue.

**Comment by mikepenz** [comment]
@javiersantos the **CommunityMaterial** is no different to the **GoogleMaterial** icon addon. which is really strange. both a normal icon fonts. the SNAPSHOT variant of the **GoogleMaterial** icon addon uses the same unicode range for the characters. 

If i only could reproduce it somehow

**Comment by javiersantos** [comment]
It seems a really weird issue. I was using both icon packs (`gmd` and `cmd`), only the icons of the first one were showing properly.

I will help you more if I could do, but I'm not able to reproduce on any of my devices. It could even be an issue of the ROM build.

**Comment by mikepenz** [comment]
It is really weird. 

Thank you so much for your time.

**Comment by timrae** [comment]
@mikepenz 
Thanks, I've decided to just use pngs for all our icons as this and #85 basically make this library unusable for us. It was a nice idea, thanks for all of your work!

**Comment by mikepenz** [comment]
@timrae i see and i'm sorry that there are limitations of icon fonts. 

About the wrong icon issue. I have no more idea how to fix, and i'm afraid i can't solve it as long as i have no possibility to reproduce it on my end.

**Comment by mikepenz** [comment]
@javiersantos can you please ask your friend which theme he is using. i hope i can somehow reproduce the issue.

**Comment by mikepenz** [comment]
Installed CM12.1 on a HTC M7 and tried 10 different themes. I really can't reproduce it. sorry.

**Comment by javiersantos** [comment]
He isn't using any third-party theme @mikepenz. If it is helpful for you, this is the ROM installed on his  device: http://forum.xda-developers.com/oneplus-one/development/rom-euphoria-os-beta-0-4-t2960226

Hope it helps you.

**Comment by javiersantos** [comment]
However, I have trying the Euphoria 5.1 ROM on a Moto G 2013 but I'm not able to reproduce the issue.

**Comment by mikepenz** [comment]
@javiersantos i'm afraid it is an issue caused by this rom. 

To be fair i'm not sure if i should or even can support this. 


i just tried the theme which is linked in the euphoria thread. also not possible to reproduce this bug. but he can reproduce it all the time with this rom. after rebooting etc?

**Comment by javiersantos** [comment]
Yep. Some days ago I created for him a sample APK with some IconicsImageViews (latest Snapshot). His device wasn't showing any icon after rebooting.

**Comment by mikepenz** [comment]
@javiersantos and he also does not use something regarding xposed?

**Comment by javiersantos** [comment]
Nope @mikepenz, he is not using the Xposed framework.

**Comment by mikepenz** [comment]
@javiersantos thank you so much for all your time and that you answer all those questions. 

I am really afraid that this bug can't be really reproduced or fixed. 
i am sure there is a root cause for this somewhere, but as it is working for all stock devices (+ stock manufactur devices) + most custom roms i still think Android-Iconics can be used in production. 

I hope some day we are able to find the root cause for this. I will close it for now until we are able to reproduce it on another device. 

 Additional i can also publish the changes of the google material icons addon

**Comment by mikepenz** [comment]
@javiersantos do you use an IconicsTextView somewhere or use the Android-Iconics icons within a `TextView` / `Button` somewhere?

**Comment by mikepenz** [comment]
@javiersantos i have a new font source for the Google Material Icons as i've found that if you used the old `.ttf` inside your `TextView` it was badly missaligend. 

I have released a new version v2.1.2.1 of the `GoogleMaterial` font addon. 

Could you please try if this one fixes the mapping issue?

THANK YOU so much :)

The new source is this one:
http://zavoloklom.github.io/material-design-iconic-font/

**Comment by javiersantos** [comment]
Sure @mikepenz. I'm busy today, but I will check this new update at the end of this week and I will let you know the results.

**Comment by justinkruit** [comment]
Justin here, from the post on G+. I've an Opo, using Euphoria, and as theme Prozt, BlueSeas. I will try around with an other theme again. The weirdest part imo is, that I'm the only one with the problem, and even a friend of me with euphoria and an opo doesn't have the problem.

**Comment by mikepenz** [comment]
@justinkruit you are the second one with this rom having the issue. the collegue from @javiersantos also uses Euphoria for is One Plus One. I have the fear that exact this ROM breaks the mapping.

**Comment by justinkruit** [comment]
@mikepenz and first it wasn't broken. Only recently. Now on default theme, still having the problem. And what I find even weirder, is that in the demo app, everything is normal, and looks like it should. 
![screenshot_2015-11-04-12-49-51](https://cloud.githubusercontent.com/assets/1642830/10937365/9f0a2cdc-82f2-11e5-89f0-63114e3b7d68.png)
![screenshot_2015-11-04-12-50-02](https://cloud.githubusercontent.com/assets/1642830/10937371/a63d9750-82f2-11e5-98ef-d8aa0114ef8c.png)

**Comment by javiersantos** [comment]
I've created two APKs with the new updates of Android Iconics and Google Material Icons.

[com.github.javiersantos.materialiconsexample](http://apkshared.net/d08)
[com.github.javiersantos.materialiconsexample.proguard](http://apkshared.net/d09)

Hope it helps.

**Comment by justinkruit** [comment]
@javiersantos I'm only seeing one icon, added a screenshot. 
And should I make stuff even weirder? The Android-Iconics app first rendered every icon barely, but my app did work. Now my app doesn't work, but in Android-Iconics, everything is now rendering correctly. I'm really losing track of what is happening right now. 
![screenshot_2015-11-04-13-01-21](https://cloud.githubusercontent.com/assets/1642830/10937649/b2d533d6-82f4-11e5-8239-bcd8b389ea6e.png)
![screenshot_2015-11-04-13-00-28](https://cloud.githubusercontent.com/assets/1642830/10937650/b72ee0b2-82f4-11e5-8e8b-2fc7bc2abfa3.png)

**Comment by javiersantos** [comment]
It was my fault, I forgot to change the `iiv_icon` with the new source. It is a bit confusing now, because there are not using the same name (@justinkruit so you have to update them).

[com.github.javiersantos.materialiconsexample](http://apkshared.net/5ci)
[com.github.javiersantos.materialiconsexample.proguard](http://apkshared.net/5cj)

**Comment by justinkruit** [comment]
@javiersantos seeing 4 icons now. I'll start my laptop to update some libs, looking if that will help. 
![screenshot_2015-11-04-13-20-26](https://cloud.githubusercontent.com/assets/1642830/10937956/ee14b488-82f6-11e5-867a-414b3ea50501.png)

**Comment by mikepenz** [comment]
@javiersantos i noted this in the `README.md` (probably will move this to a new `MIGRATION.md`) that the mapping changed as the new font (which uses the same icons) has a different mapping. 
I know that it's bad that the mapping names changed but the font itself also is better as the icons are aligned vertical centered inside the font. so if you use them inside an TextView they are centered. 

The new sample app of Android-Iconics (from github) uses v2.0.0 and the new icons. The play store variant was not yet updated.

**Comment by javiersantos** [comment]
@mikepenz good news. My friend's device is now showing the icons properly too :+1:

**Comment by mikepenz** [comment]
@javiersantos so it seems the new GoogleMaterial font fixes it ;). That's awesome.

**Comment by justinkruit** [comment]
@mikepenz how exactly do I update the GoogleMaterial font if it's included in the drawer library?

**Comment by mikepenz** [comment]
@justinkruit the `GoogleMaterial` font is not included in the drawer library. The drawer library only contains the core. You have added the `GoogleMaterial` font addon to your dependencies. Just update it there to `v2.1.2.1` remember that it will change the mapping names. Here's the cheatsheet of them:
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html

I'm really sorry that the mapping changed, but it seems the `Google` team mapped and packed the icon font wrong. So i switched to the external project which uses exact the same icons

**Comment by justinkruit** [comment]
@mikepenz all working now, after some hours of work. (had some problems with updating, all fixed.) Thank you really much, looking forward for more of your work. :smile: 
![screenshot_2015-11-04-16-30-15](https://cloud.githubusercontent.com/assets/1642830/10942756/ae9678ee-8311-11e5-88ef-8c55ddbee99b.png)

**Comment by mikepenz** [comment]
@justinkruit which problems did you have with updating? were it the new `GoogleMaterial` icon mappings? If yes, I'm really sorry for this, but this is caused by the new `*.ttf` i use from this project: http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html.
If something else, could i have helped you to avoid / fix this problem?

**Comment by justinkruit** [comment]
@mikepenz the icon mappings weren't that much of a problem, only some had a new name. The problems where with some changes in, for example, a newer version of the drawer. I was some versions behind, and after updating some stuff was broken. Most of those hours I was going thru my files and fixing the stuff that broke, mostly fixing with alt + enter or changing some lines. But all working now. :)

**Comment by mikepenz** [comment]
@justinkruit ok great :D. I hope everything was mentioned in the MIGRATION.md of the MaterialDrawer https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md

**Comment by mikepenz** [comment]
So finally i can close this issue :). 

THANK YOU ALL SO MUCH FOR HELPING. especially @javiersantos and @justinkruit
